### ISSUE TITLE
Just setting appRoot folder not working

### ISSUE THREAD

**Issue by thecodejack** [Caesar2011/denotrain#10]
I am trying to set a document root using following. For some reason, it's not working. Any idea if anything being done wrong here?

```
import {
  Application,
  Router,
} from "https://deno.land/x/denotrain@v0.4.4/mod.ts";

// Create a new application (port defualts to 3000, hostname to 0.0.0.0)
const app = new Application({
  port: 80,
  appRoot: "./site/",
// appRoot: "site/",
// appRoot: "site",
});

await app.run();
```

**Comment by Caesar2011** [comment]
What do you want to do? I think there is an misunderstanding.

**Comment by Caesar2011** [comment]
`appRoot` is supposed to be an absolute path for every other router file. This could be handy for static files or view engines. At the moment I do not use it anywhere but you could. 

To accomplish something like this, which I assume you intend to do, create a router that listens for the `/site' path and mount all your routes there. 

```ts
import {
  Application,
  Router,
} from "https://deno.land/x/denotrain@v0.4.4/mod.ts";

const app = new Application({
  port: 80
});

const router = new Router();
router.get("/subdir", () => {
    return {"json": "data"};
});

// Mount router on site
app.use("/site", router);

await app.run();
```

**Comment by thecodejack** [comment]
ok.. seems like I misunderstood the appRoot usage..I was trying to use it for making all the files pointed by appRoot config to be served automatically as static files.
