### ISSUE TITLE
Capture all requests after a certain path

### ISSUE THREAD

**Issue by Xylobol** [Caesar2011/denotrain#12]
Hello! 

I was wondering if it was possible to allow a handler to catch all requests for a certain path. For example, if we have
```
app.get("/:id/:thing", (ctx: ext.dt.Context) => {
  // do whatever here
}); 
```
would it be possible for both `/1/a` and `/1/a/b` to be handled?

**Comment by Xylobol** [comment]
Perhaps a wildcard operator could be useful for this. I haven't worked on this codebase before, but if someone experienced could point me in the right direction, it'd be appreciated.

**Comment by Caesar2011** [comment]
Assign the route handler to a variable and then use it in the `get` methods :)

**Comment by Caesar2011** [comment]
@Xylobol I have not seen that you have left a comment. what do you mean by wild card handler?

**Comment by parasg1999** [comment]
@Caesar2011 I think what he means by a wildcard handler is that this code should serve for both `/api` as well as let's sat `/api/foo`,

```javascript
app.get("/api/*", (ctx: ext.dt.Context) => {
  // do whatever here
}); 
```

Generally a get method is used with route `/*` at the end of file to look for unhandled routes and throw `error 404: Not Found`.

**Comment by Caesar2011** [comment]
For this case regular expression should do the trick. Try `/\/api\/.*/`.

Also 404 is automatically set if no body was set in the `onHandle` lifecycle. To create an error handler like this take a look at [the docs about lifecycle](https://github.com/Caesar2011/denotrain/blob/master/doc/handlers.md) or the middleware `json-error`. Which takes an occured `ClientError` and converts it into a wonderful json.

It is used in the examples `middleware`. Try to open a route that is not defined.

**Comment by parasg1999** [comment]
> For this case regular expression should do the trick. Try `/\/api\/.*/`.

@Xylobol Looks like this will do the trick for you!
