### ISSUE TITLE
How to stream video and audio content

### ISSUE THREAD

**Issue by doppelgunner** [Caesar2011/denotrain#14]
Hi, newbie here just wanted to ask if there is an easy way to stream audio to client?

**Comment by Caesar2011** [comment]
You would need an UDP socket to accomplish that. Denotrain uses an HTTP/TCP socket and thus cannot do something like that.

**Comment by doppelgunner** [comment]
ok noted, does instagram, tiktok and spotify uses udp? for audio streaming?

**Comment by Caesar2011** [comment]
Some of them, I know from Spotify, use TCP. But that does not mean, did they are using HTTP on top of that. Because this is in a HTTP Webserver, you asked the question in the wrong place. I apologise for closing. I am not able to give more advise because my lack of detailed knowledge. :)
