### ISSUE TITLE
Parsing int64 params

### ISSUE THREAD

**Issue by mrcuong1102** [Caesar2011/denotrain#15]
When I using path parameters from router with an int64 value, the automated parser return an incorrect value.
Eg:  `/:userId` -->  `/394518333870964737`
Expect: `{ userId: 394518333870964737 }`
Actual: `{ userId: 394518333870964740 }`

I think you should add a new param like "options: object" to define more option (Eg: `{ parse: false }` to prevent automated parser).

**Comment by Caesar2011** [comment]
I see. I thought about this before and I will add such an options :)

**Comment by Caesar2011** [comment]
In v0.5.4 you have `req.rawParams` next to `req.params` where the parameter is not parsed as a number.
