### ISSUE TITLE
Respond with HTML

### ISSUE THREAD

**Issue by leoncustodio** [Caesar2011/denotrain#6]
I couldn't find a way to respond with HTML, but I saw you're working on it in `Response`.

Just to document:
```
app.get("/", async (ctx) => {
  return "<h1>Hello world</h1>"; 
});
```
![Screen Shot 2020-05-15 at 6 59 22 PM](https://user-images.githubusercontent.com/15876073/82102665-3982c900-96de-11ea-8c04-9ec152e60808.png)

**Comment by Caesar2011** [comment]
You have to set the MimeType with `ctx.res.setMimeType()` to `text/html` before returning. Take a look in the `Response.ts` file. 

Also take a look in the ViewTemplate system. You can add your own ViewTemplate render engine or use the already implemented ejs engine. Take a closer look to `example/viewengine/example.ts`.

(Everything is unchecked and may be named differently but should give you an idea. I hope it is clear)

**Comment by Caesar2011** [comment]
And just for record: You do not need the async keyword if your handler is sync anyway :D . It doesn't make any difference in this case.

**Comment by leoncustodio** [comment]
Thank you for the quick reply! 🙏
